
![logo itq](img/itqlogo.jpeg)

**TERCER MODULO - PANDAS II**

![logo_python](img/pythonlogo.jpeg)

*Gabriel Culqui*

In [26]:
import pandas as pd
import numpy as np

In [27]:
pd.__version__

'2.3.3'

# Operaciones en pandas

#### Búsqueda

In [28]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  0  1  3
1  1  3  2

In [29]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [30]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B     C
0  False  False  True
1  False   True  True

In [31]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

0

       A      B      C
0  False  False  False
1  False  False  False

[[False False False]
 [False False False]]

numpy.ndarray

In [32]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

3

       A      B     C
0  False  False  True
1  False   True  True

#### Ordenación

In [33]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
4   8   8  13  17
2  18   6   5  17
1  17  13   8  18
0   2   4   4  13
3   7   2   2   7

In [34]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   8   8  13  17
3   7   2   2   7
2  18   6   5  17
1  17  13   8  18
0   2   4   4  13

    D   A   C   B
4   8   8  13  17
2  18   6   5  17
1  17  13   8  18
0   2   4   4  13
3   7   2   2   7

In [35]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
4   8  13  17   8
2  18   5  17   6
1  17   8  18  13
0   2   4  13   4
3   7   2   7   2

In [36]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
3   7   2   2   7
0   2   4   4  13
2  18   6   5  17
4   8   8  13  17
1  17  13   8  18

In [37]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    C   A   D   B
4  13   8   8  17
2   5   6  18  17
1   8  13  17  18
0   4   4   2  13
3   2   2   7   7

In [38]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
1  17  13   8  18
4   8   8  13  17
2  18   6   5  17
0   2   4   4  13
3   7   2   2   7

#### Ranking
- Construir un ranking de valores

In [39]:
display(frame)

    D   A   C   B
1  17  13   8  18
4   8   8  13  17
2  18   6   5  17
0   2   4   4  13
3   7   2   2   7

In [40]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
1  3.0  2.0  1.0  4.0
4  2.0  2.0  3.0  4.0
2  4.0  2.0  1.0  3.0
0  1.0  3.0  3.0  4.0
3  4.0  2.0  2.0  4.0

In [41]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

13
8
5
4
2

# Operaciones

Operaciones matemáticas entre objetos

In [42]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  25  88  19  34
1  53  98  26   4
2  35  47  46  81
3   9  78  92  17

    0   1   2   3
0   0  82  81  12
1  58  58  72  81
2   0  77  51  10
3   9  92  88  45

In [43]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2   3
0   25  170  100  46
1  111  156   98  85
2   35  124   97  91
3   18  170  180  62

In [44]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -25  -6  62 -22
1   5 -40  46  77
2 -35  30   5 -71
3   0  14  -4  28

In [45]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  25  88  19  34
1  53  98  26   4
2  35  47  46  81
3   9  78  92  17

    0   1   2
0  93  95  71
1   7  45  13
2  53  94  80

       0      1      2   3
0  118.0  183.0   90.0 NaN
1   60.0  143.0   39.0 NaN
2   88.0  141.0  126.0 NaN
3    NaN    NaN    NaN NaN

In [46]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0  118.0  183.0   90.0  34.0
1   60.0  143.0   39.0   4.0
2   88.0  141.0  126.0  81.0
3    9.0   78.0   92.0  17.0

Operadores aritméticos solo válidos en elementos aceptables

In [47]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

pandas se basa en NumPy, np operadores binarios y unarios son aceptables 

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por columna

In [ ]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis = 0)) # diferencia por columna

In [ ]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

| Operación | Descripción |
|:----------|:------------|
| count | Número de valores no NaN |
| describe | Conjunto de estadísticas sumarias|
| min, max | Valores mínimo y máximo |
| argmin, argmax | Índices posicionales del valor mínimo y máximo |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo |
| sum | Suma de los elementos |
| mean | Media de los elementos |
| median | Mediana de los elementos |
| mad | Desviación absoluta media del valor medio |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos |
| cumsum | Suma acumulada de los elementos |
| diff | Diferencia aritmética de los elementos |

In [ ]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30], 
               "puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

In [ ]:
# operadores básicos
print(frame.sum())

display(frame)
print(frame.sum(axis=1, numeric_only=True))

In [ ]:
frame.mean(numeric_only=True)

In [ ]:
frame.cumsum()

In [ ]:
frame.count(axis=1)

In [ ]:
print(frame['edad'].std())

In [ ]:
frame['edad'].idxmax()

In [ ]:
frame['puntos'].idxmin()

In [ ]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())

display(frame[frame['puntos'] == frame['puntos'].max()])

In [ ]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [ ]:
display(frame)

## Agregaciones

In [ ]:
display(frame)
df = frame.groupby('genero').count()
display(df)

In [ ]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

In [ ]:
display(frame.groupby('genero').mean(numeric_only=True))

In [ ]:
display(frame.groupby('genero').max())

In [ ]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

In [ ]:
# Filtrado de los datos en el que el conjunto no supera una media determinada 
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

## Correlaciones

pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos
- https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [ ]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, sep='\s+', header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?', engine='c')

In [ ]:
display(mpg_data.sample(5))

In [ ]:
display(mpg_data.describe(include='all'))

In [ ]:
mpg_data.info()

### Correlaciones entre valores

In [ ]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

In [ ]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

### Correlaciones entre todos los valores

In [ ]:
mpg_data.corr(numeric_only=True)

In [ ]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

In [ ]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [ ]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [ ]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

In [ ]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax()  #consigo misma....

In [ ]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

In [ ]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

## Ejercicios

- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb

**EJERCICIO 1**
1. Import pandas under the alias pd.

In [ ]:
import pandas as pd

**EJERCICIO 2**

2. Print the version of pandas that has been imported.

In [ ]:
print(pd.__version__)

**EJERCICIO 3**

3. Print out all the version information of the libraries that are required by the pandas library.

In [ ]:
pd.show_versions()

**EJERCICIO 4**

In [ ]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

4. Create a DataFrame df from this dictionary data which has the index labels.

In [ ]:
df = pd.DataFrame(data, index=labels)  # Se construye la tabla relacionando cada dato con su etiqueta
print(df)

**EJERCICIO 5**

5. Display a summary of the basic information about this DataFrame and its data (hint: there is a single method that can be called on the DataFrame).

In [ ]:
df = pd.DataFrame(data, index=labels)
df.info()

#Se usa .info para extraer la información básica

**EJERCICIO 6**

6. Return the first 3 rows of the DataFrame df.

In [ ]:
filas3 = df.head(3)
print(filas3)

**EJERCICIO 7**
  
7. Select just the 'animal' and 'age' columns from the DataFrame df.

In [ ]:
columnas = df[['animal', 'age']]
print(columnas)

**EJERCICIO 8**

8. Select the data in rows [3, 4, 8] and in columns ['animal', 'age'].

In [ ]:
result = df.iloc[[3, 4, 8], [0, 1]]
print(result)

**EJERCICIO 9**

9. Select only the rows where the number of visits is greater than 3.

In [ ]:
result = df[df['visits'] > 3]
print(result)

**EJERCICIO 10**

10. Select the rows where the age is missing, i.e. it is NaN.

In [ ]:
edad_nula = df[df['age'].isnull()]
print(edad_nula)

**EJERCICIO 11**

11. Select the rows where the animal is a cat and the age is less than 3.

In [ ]:
print(df)

df.query("animal=='cat' and age<3")

**EJERCICIO 12**

12. Select the rows the age is between 2 and 4 (inclusive).

In [ ]:
df.query("age>=2 and age<=4")

**EJERCICIO 13**

13. Change the age in row 'f' to 1.5.

In [ ]:
df.at['f','age']=1.5
print(df)

**EJERCICIO 14**

14. Calculate the sum of all visits in df (i.e. find the total number of visits).

In [ ]:
print(df['visits'].sum())
print(df['visits'].sum(axis=0))

**EJERCICIO 15**

15. Calculate the mean age for each different animal in df.

In [51]:
display(df.groupby("animal")['age'].mean())

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64